name: DevOps Monitoring CI

on:
  push:
    branches:
      - main

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check files
        run: |
          ls -la
          test -f README.md
          test -f Makefile
          test -f docker/docker-compose.yaml
          test -f docker/prometheus/prometheus.yml
          test -f docker/prometheus/alert.rules.yml

      - name: Validate docker compose
        run: docker compose -f docker/docker-compose.yaml config

      - name: Run Prometheus config check
        run: |
          docker run --rm \
            --entrypoint promtool \
            -v ${{ github.workspace }}/docker/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml \
            -v ${{ github.workspace }}/docker/prometheus/alert.rules.yml:/etc/prometheus/alert.rules.yml \
            prom/prometheus \
            check config /etc/prometheus/prometheus.yml
